import {BORDERS,effective,cardDistribution,borderProbabilities} from './core.js?v=6';

// Count sampling adapted from Hit Calculator's roll-sim-worker-v39.js.
// https://github.com/DaddyDrag0/HitCalculator/blob/main/roll-sim-worker-v39.js
export function randomSource(seed){let state=seed>>>0;return{unit53:()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/4294967296)}}
function normal(random){return Math.sqrt(-2*Math.log(Math.max(Number.MIN_VALUE,random.unit53())))*Math.cos(2*Math.PI*random.unit53())}
function poisson(lambda,random){if(!lambda)return 0;if(lambda<24){const stop=Math.exp(-lambda);let product=1;for(let k=0;k<128;k++){product*=Math.max(Number.MIN_VALUE,random.unit53());if(product<=stop)return k}}return Math.max(0,Math.round(lambda+Math.sqrt(lambda)*normal(random)))}
export function binomial(n,p,random){n=Math.max(0,Math.floor(n));p=Math.max(0,Math.min(1,p));if(!n||!p)return 0;if(p===1)return n;if(p>.5)return n-binomial(n,1-p,random);if(n<=64){let hits=0;for(let i=0;i<n;i++)if(random.unit53()<p)hits++;return hits}const mean=n*p;if(mean<24&&p<=.08)return Math.min(n,poisson(mean,random));const z=normal(random),skew=(1-2*p)/6*(z*z-1);return Math.max(0,Math.min(n,Math.round(mean+Math.sqrt(mean*(1-p))*z+skew)))}
export function multinomial(n,probabilities,random,preparedOrder){const counts=Array(probabilities.length).fill(0);let remaining=Math.floor(n),mass=probabilities.reduce((a,b)=>a+b,0);const order=preparedOrder||probabilities.map((p,i)=>({p,i})).filter(x=>x.p>0).sort((a,b)=>a.p-b.p);for(let j=0;j<order.length;j++){const {p,i}=order[j];const count=j===order.length-1?remaining:binomial(remaining,p/mass,random);counts[i]=count;remaining-=count;mass=Math.max(0,mass-p)}return counts}
export function periodicGroups(cycles,periodic=[]){const gcd=(a,b)=>b?gcd(b,a%b):a,count=periodic.length,groups=[];const multiples=mask=>{let period=1;for(let i=0;i<count;i++)if(mask&(1<<i))period=period/gcd(period,periodic[i].every)*periodic[i].every;return Math.floor(cycles/period)};for(let mask=0;mask<(1<<count);mask++){let amount=0,mult=1;for(let i=0;i<count;i++)if(mask&(1<<i))mult*=periodic[i].mult;const rest=((1<<count)-1)^mask;for(let sub=rest;;sub=(sub-1)&rest){const bits=sub.toString(2).replace(/0/g,'').length;amount+=(bits%2?-1:1)*multiples(mask|sub);if(!sub)break}if(amount>0)groups.push({cycles:amount,mult})}return groups}
export function simulationOutcomes(s,data,stats,mult=1){const bp=borderProbabilities(s,stats),outcomes=[];for(const {card,p:cardP} of cardDistribution(s,data,stats.Luck*mult))for(let mask=0;mask<32;mask++){let p=cardP,rarity=card.rarityValue;const borders=[];for(let i=0;i<BORDERS.length;i++){const b=BORDERS[i],chance=b==='Fabled'&&card.rarityValue>s.fabledMax?0:bp[b];p*=mask&(1<<i)?chance:1-chance;if(mask&(1<<i)){borders.push(b);rarity*=data.borderRarity[b]}}if(!p)continue;const boost=card.weatherLock===s.weather?(data.weather[s.weather]?.boostMultiplier||1):1,hp=Math.floor((10+rarity**.35*5)*boost);outcomes.push({name:card.name,baseRarity:card.rarityValue,rarity,borders,mask,p,score:hp+2*Math.floor(hp/2),hit:(s.goal.kind==='card'?card.name===s.goal.card:card.rarityValue>=s.goal.rarity)&&s.goal.borders.every(b=>borders.includes(b))})}outcomes.sort((a,b)=>a.score-b.score||a.rarity-b.rarity);let below=0;for(let i=0;i<outcomes.length;){let j=i,mass=0;while(j<outcomes.length&&outcomes[j].score===outcomes[i].score&&outcomes[j].rarity===outcomes[i].rarity)mass+=outcomes[j++].p;for(let k=i;k<j;k++)outcomes[k].p*=1-stats.LuckyHandChance+stats.LuckyHandChance*(2*below+mass);below+=mass;i=j}return outcomes}
export function prepareSimulation(s,data,seconds){const stats=effective(s,data),cycles=Math.floor(seconds/stats.RollInterval);return{stats,cycles,seconds,groups:periodicGroups(cycles,stats.periodic).map(g=>{const outcomes=simulationOutcomes(s,data,stats,g.mult),probabilities=outcomes.map(o=>o.p),order=probabilities.map((p,i)=>({p,i})).filter(x=>x.p>0).sort((a,b)=>a.p-b.p);return {...g,outcomes,probabilities,order}})}}
export function simulateSession(prepared,seed){const random=randomSource(seed),borderTotals=Object.fromEntries(BORDERS.map(b=>[b,0])),combos={},inventory=new Map();let cards=0,hits=0,best=null;for(const group of prepared.groups){let amount=group.cycles;for(const [key,extra] of [['DoubleRollChance',1],['RollTwiceChance',2],['TripleRollChance',2]])amount+=extra*binomial(group.cycles,prepared.stats[key],random);const counts=multinomial(amount,group.probabilities,random,group.order);for(let i=0;i<counts.length;i++){const count=counts[i];if(!count)continue;const o=group.outcomes[i],key=o.name+'|'+o.mask;cards+=count;if(o.hit)hits+=count;combos[o.mask]=(combos[o.mask]||0)+count;for(const b of o.borders)borderTotals[b]+=count;const row=inventory.get(key)||{name:o.name,baseRarity:o.baseRarity,rarity:o.rarity,borders:o.borders,mask:o.mask,count:0,hit:o.hit};row.count+=count;inventory.set(key,row);if(!best||o.rarity>best.rarity)best={...row}}}return{seed,cycles:prepared.cycles,seconds:prepared.seconds,cards,hits,uniqueCards:new Set([...inventory.values()].map(o=>o.name)).size,borderTotals,combos,best,inventory:[...inventory.values()].sort((a,b)=>b.rarity-a.rarity)}}
export function aggregateSessions(runs){const inventory=new Map(),borderTotals=Object.fromEntries(BORDERS.map(b=>[b,0])),combos={};let cards=0,hits=0,best=null;for(const run of runs){cards+=run.cards;hits+=run.hits;if(run.best&&(!best||run.best.rarity>best.rarity))best=run.best;for(const b of BORDERS)borderTotals[b]+=run.borderTotals[b];for(const [mask,count] of Object.entries(run.combos))combos[mask]=(combos[mask]||0)+count;for(const row of run.inventory){const key=row.name+'|'+row.mask,item=inventory.get(key)||{...row,count:0,runsHit:0};item.count+=row.count;item.runsHit++;inventory.set(key,item)}}return{runCount:runs.length,cards,hits,cycles:runs.reduce((n,r)=>n+r.cycles,0),seconds:runs[0]?.seconds||0,hitRuns:runs.filter(r=>r.hits>0).length,uniqueCards:new Set([...inventory.values()].map(o=>o.name)).size,borderTotals,combos,best,inventory:[...inventory.values()].sort((a,b)=>b.rarity-a.rarity)}}
