import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaults,normalize,effective} from '../core.js';
import {buildDefaults,skillBudget,skillSelection,shopAction,luckVariants,corruptedCost,corruptedRefund,corruptedRemainingCost,buyAllCorrupted} from '../build.js';
const data=JSON.parse(fs.readFileSync(new URL('../data/game.json',import.meta.url))),setup=()=>normalize({...defaults(data),build:buildDefaults()},data),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
test('Index is the sole fixed SP source; blank and removed extras cannot grant skill points',()=>{const s=setup();assert.equal(skillBudget(s.build,data),0);assert.ok(skillSelection(s.build,'V2_FORTUNE_CORE_1',true,data).error);s.build.index=100;s.build.extraSkillPoints=999;assert.equal(skillBudget(s.build,data),10);const clean=normalize(s,data);assert.ok(!Object.hasOwn(clean.build,'extraSkillPoints'));s.build.index=null;assert.equal(skillBudget(s.build,data),0)});
test('Lowering Index trims dependent skills to the new fixed budget',()=>{const s=setup();s.build.index=100;s.build.skills=skillSelection(s.build,'V2_FORTUNE_CORE_3',true,data).ids;s.build.index=0;assert.deepEqual(normalize(s,data).build.skills,[])});
test('Legendary and Mythic Shiny/Awakened stack; Fabled potion imports are removed',()=>{const s=setup();s.build.potions=['ShinyPotionLegendary','ShinyPotionMythic','AwakenedPotionLegendary','AwakenedPotionMythic'];const r=effective(s,data);close(r.ShinyLuck,(1+1+1.6)*1.05);close(r.AwakenedLuck,(1+1.2+2)*1.05);s.build.potions.push('FabledPotion');assert.ok(!normalize(s,data).build.potions.includes('FabledPotion'))});
test('Screenshot-confirmed achievement and Corrupted bonuses feed totals exactly once',()=>{const s=setup();s.build.under10M=false;s.build.achievements=['DreamRealm','Ca2e','Creator','HallAwakened5','TheUnwritten'];s.build.corrupted={CorruptedFortune:5,AwakenedRitual:10,CorruptedCalling:7,EchoRoll:7,FracturedRoll:5};const r=effective(s,data);close(r.Luck,1+1+2+2+6+40);close(r.AwakenedLuck,1+.3+.1+.2+.3+30);close(r.CorruptedLuck,1+.7+7);close(r.FabledLuck,2+.2+.4);close(r.DoubleRollChance,.07);close(r.TripleRollChance,.025);assert.equal(data.achievements.length,19)});
test('Corrupted costs match all screenshots, refunds return the full cumulative spend, and purchases enforce balances',()=>{const expected=[[50,78,120,186,289,447,693,1075,1666],[40,62,96,149,231,358,555,860,1333],[85,140,231,382,630,1040,1715,2830,4670],[60,93,144,223,346,537,832,1290,1999],[125,219,383,670,1172,2052]];data.corruptedUpgrades.forEach((d,i)=>{expected[i].forEach((cost,level)=>{assert.equal(Math.round(d.costFormula.base*d.costFormula.growth**level),cost);assert.equal(corruptedCost(d,level),cost);assert.equal(corruptedRefund(d,level),expected[i].slice(0,level).reduce((a,b)=>a+b,0))});assert.equal(corruptedCost(d,d.maxLevel),null)});const s=setup();s.build.corrupted.CorruptedFortune=5;s.build.currencies.corrupted=446;assert.ok(shopAction(s.build,'corrupted','CorruptedFortune',1,data).error);s.build.currencies.corrupted=447;assert.deepEqual(shopAction(s.build,'corrupted','CorruptedFortune',1,data),{level:6,balance:0});s.build.corrupted.CorruptedFortune=6;s.build.currencies.corrupted=0;assert.deepEqual(shopAction(s.build,'corrupted','CorruptedFortune',-1,data),{level:0,balance:1170})});
test('Own everything prices only remaining Corrupted levels and refuses unaffordable purchases',()=>{const s=setup();assert.equal(corruptedRemainingCost(s.build,data),45607);s.build.currencies.corrupted=45606;assert.ok(buyAllCorrupted(s.build,data).error);s.build.currencies.corrupted=45607;const r=buyAllCorrupted(s.build,data);assert.equal(r.balance,0);s.build.corrupted=r.levels;assert.equal(corruptedRemainingCost(s.build,data),0);for(const d of data.corruptedUpgrades)assert.equal(r.levels[d.id],d.maxLevel);s.build.corrupted.CorruptedFortune=5;assert.equal(corruptedRemainingCost(s.build,data),7186-723)});
test('Every gold upgrade uses corrected 25/15/1 caps and blocks the next purchase at maximum',()=>{const s=setup();s.build.currencies.tower=10000;for(const d of data.towerShop){const expected=d.id==='ThirdRelicSlot'?1:['DoubleRollChance','RollTwiceChance','LuckyHandChance'].includes(d.id)?15:25;assert.equal(d.maxLevel,expected);s.build.tower[d.id]=expected;assert.ok(shopAction(s.build,'tower',d.id,1,data).error);s.build.tower[d.id]=expected-1;assert.equal(shopAction(s.build,'tower',d.id,1,data).level,expected)}});

test('Vaeloryn supports three correlated periodic boosts, without making permanent Luck ×40',()=>{const s=setup();s.build.under10M=false;s.build.achievements=['Vaeloryn'];s.build.relics=[{id:'RelicOfBonus',border:1},{id:'WeightedDice',border:1}];const r=effective(s,data);close(r.Luck,1);const variants=luckVariants(r);close(variants.reduce((a,v)=>a+v.weight,0),1);close(variants.find(v=>v.mult===320).weight,1/20000);assert.ok(normalize(s,data).badges.includes('VoidWorldBadge'))});
test('Removed bonus/cap-extension controls do not survive profile imports',()=>{const s=setup();s.build.extras=[{name:'old',flat:{Luck:999},percent:{}}];s.build.observed={Luck:123};s.build.towerCapExtra=100;const clean=normalize(s,data);assert.deepEqual(clean.build.extras,[]);assert.deepEqual(clean.build.observed,{});assert.ok(!Object.hasOwn(clean.build,'towerCapExtra'));close(effective(clean,data).Luck,1);assert.equal(data.towerShop.find(d=>d.id==='FabledLuck').maxLevel,25)});
