import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaults,normalize,effective,evaluate,optimizePoints,validPoints,artifactBonuses,artifactSlots,profileWarnings,fastProbability,batchDistribution} from '../core.js';
import {buildDefaults,skillClosure,removeSkill,calculateBuild,luckVariants} from '../build.js';
const data=JSON.parse(fs.readFileSync(new URL('../data/game.json',import.meta.url))),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)),`${a} != ${b}`);
function setup(){const s=defaults(data);s.build=buildDefaults();return normalize(s,data)}
test('Build catalog has all 102 unique nodes with real prerequisites and complete equipment',()=>{assert.equal(data.skillNodes.length,102);assert.equal(new Set(data.skillNodes.map(x=>x.id)).size,102);for(const node of data.skillNodes)for(const req of node.requires)assert.ok(data.skillNodes.some(n=>n.id===req),`${node.name}: ${req}`);assert.equal(Object.keys(data.craftedArtifacts).length,13);assert.equal(Object.keys(data.relics).length,16);assert.equal(Object.keys(data.potions).length,24)});
test('Starting values, exact point gains, and under-10M boundary derive totals without entered stats',()=>{const s=setup();s.rolls=9999999;s.points={Luck:20,Shiny:10,Awakened:10,Void:10};s.stats.Luck=999;const r=effective(s,data);close(r.Luck,11*1.25);close(r.ShinyLuck,1.5);close(r.AwakenedLuck,2);close(r.VoidLuck,2.5);close(r.FabledLuck,2);s.rolls=1e7;close(effective(s,data).Luck,11)});
test('Selecting Transcendence closes both paths and mastery requirements; removals cascade',()=>{const ids=skillClosure(['V5_TRANSCEND_FINAL'],data);assert.ok(ids.includes('V5_TRANSCEND_STAR_2'));assert.ok(ids.includes('V5_TRANSCEND_ABYSS_2'));assert.ok(ids.includes('V4_CORRUPTED_MASTERY'));assert.equal(ids.length,81);const remaining=removeSkill(ids,'V5_TRANSCEND_STAR_1',data);assert.ok(!remaining.includes('V5_TRANSCEND_FINAL'));assert.ok(remaining.includes('V5_TRANSCEND_ABYSS_2'))});
test('Fortune flat and percentage bonuses add as ComputeBonuses; pass final Shiny multiplier is separate',()=>{const s=setup();s.build.skills=skillClosure(['V3_FORTUNE_MASTERY'],data);s.build.passes.Shiny=true;const result=calculateBuild(s,data,s.points,artifactBonuses(s,[],data));const row=result.rows.find(x=>x.name==='Skill tree');close(row.flat.Luck,36);close(row.percent.Luck,.10);close(row.flat.LuckyHandChance,.23);close(result.stats.Luck,37*1.10);close(result.stats.ShinyLuck,1.5*1.1)});
test('Crafted artifacts, relic borders, Index Sets and Tower levels all feed the build',()=>{const s=setup();s.build.crafted='RuinedClover';s.build.relics=[{id:'OldBoot',border:6}];s.build.sets=['StarterWorld'];s.build.tower.Luck=3;s.build.tower.AwakenedLuck=2;const r=effective(s,data);close(r.Luck,1+.5+10+2+6);close(r.ShinyLuck,1.1);close(r.AwakenedLuck,1.8);s.build.towerAwakenedGain=.3;close(effective(s,data).AwakenedLuck,1.6)});
test('Void upgrades scale artifact bonuses, potion power, final Void Luck and slot count',()=>{const s=setup();s.build.void={PASlots:2,VoidArtifactPower:2,VoidPotionPower:5,VoidLuckPct:3};s.build.passes.ArtifactSlots=true;s.artifact.rarity='Celestial';s.artifact.slots=[{id:'Luck',value:100,locked:false},{id:'LuckMult',value:1.5,locked:false}];s.build.potions=['LuckPotionLarge'];const n=normalize(s,data),r=effective(n,data),pa=artifactBonuses(n,n.artifact.slots,data);close(pa.flat.Luck,143);close(pa.mult.Luck,1.715);close(r.PotionPowerMult,1.2);close(r.Luck,(1+143+3.6)*1.715);close(r.VoidLuck,1.09);assert.equal(artifactSlots(n,data),9);n.rolls=1e8;assert.equal(artifactSlots(n,data),11)});
test('Mythic potion percentage, Parkour and Heavenly Luck stay distinct; model order is selectable',()=>{const s=setup();s.build.potions=['LuckPotionMythic','LuckOrbBuff','HeavenlyLuckPotion'];const r=effective(s,data);close(r.Luck,(1+8+3)*1.05*1.1*1.4);s.build.skills=['CONST_LUCK'];s.artifact.slots=[{id:'LuckMult',value:1.5,locked:false}];const separate=effective(s,data).Luck;s.build.percentOrder='combined';const combined=effective(s,data).Luck;assert.ok(separate>combined)});
test('Weather applies once, Dungeon estimate is opt-in and observed values never affect totals',()=>{const s=setup();s.weather='GlaringSun';s.build.observed.Luck=999;close(effective(s,data).Luck,7*1.1);s.build.inDungeon=true;s.build.floor=30;const r=effective(s,data);close(r.Luck,7*1.1+48);close(r.ShinyLuck,2.2);close(r.AwakenedLuck,3);close(r.CorruptedLuck,2)});
test('Periodic relic weights use synchronized intersections and never become flat Luck',()=>{const s=setup();s.build.passes.TwoRelic=true;s.build.relics=[{id:'RelicOfBonus',border:1},{id:'WeightedDice',border:1}];const r=effective(s,data),variants=luckVariants(r);close(r.Luck,1);close(variants.reduce((n,v)=>n+v.weight,0),1);close(variants.find(v=>v.mult===8).weight,1/50);const expected=variants.reduce((n,v)=>n+v.weight*fastProbability(s,data,{...r,Luck:r.Luck*v.mult,periodic:[]}),0);close(evaluate(s,data).probability,expected)});
test('Build point optimization agrees with independent brute force under tree and artifact multipliers',()=>{const s=setup();s.rolls=1500000;s.build.skills=['CONST_LUCK'];s.artifact.slots=[{id:'LuckMult',value:1.2,locked:false}];const actual=optimizePoints(s,data);let best=0;for(let l=0;l<=20;l++)for(let sh=0;sh<=10;sh++)for(let aw=0;aw<=10;aw++)for(let v=0;v<=10;v++)if(l+sh+aw+v<=30)best=Math.max(best,evaluate(s,data,{Luck:l,Shiny:sh,Awakened:aw,Void:v}).hitsPerHour);close(actual.result.hitsPerHour,best);assert.ok(validPoints(actual.points,30,data));s.points=actual.points;close(evaluate(s,data).hitsPerHour,actual.result.hitsPerHour)});
test('Impossible constellation/relic builds warn, and imported identifiers and numeric extremes are bounded',()=>{const s=setup();s.build.skills=['CONST_LUCK','CONST_SHINY','CONST_VOID'];s.build.relics=[{id:'OldBoot',border:1},{id:'OldBoot',border:6}];assert.ok(profileWarnings(s,data).some(w=>w.includes('Constellations')));assert.ok(profileWarnings(s,data).some(w=>w.includes('once')));s.build.skills.push('<script>');s.build.void.PASlots=999;s.build.tower.ThirdRelicSlot=999;const clean=normalize(s,data);assert.ok(!clean.build.skills.includes('<script>'));assert.equal(clean.build.void.PASlots,2);assert.equal(clean.build.tower.ThirdRelicSlot,1)});
